#!/usr/bin/env bash
# Displays a message endlessly and ignores SIGTERM by printing a message

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
