#!/usr/bin/env bash
# Prints a message indefinitely and ignores SIGTERM by displaying a custom message

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
